export const MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY

export const IPFS_CLIENT_PROJECT = process.env.NEXT_PUBLIC_IPFS_CLIENT_PROJECT
export const IPFS_CLIENT_SECRET = process.env.NEXT_PUBLIC_IPFS_CLIENT_SECRET

export const APPWRITE_API_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_API_ENDPOINT
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID
export const APPWRITE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID

export const APPWRITE_EVENTS_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID
